### ISSUE TITLE
Central Command shows PRE_DEPLOYMENT__OFF state which no longer exists.

### ISSUE THREAD

**Issue by tsaubergine** [jaiarobotics/jaiabot#100]
![image](https://user-images.githubusercontent.com/732276/182093297-ce0e9c9f-688e-42fc-9b48-fccdc8b9e05a.png)

**Comment by tsaubergine** [comment]
Once you get in this state you can't activate the bots.

**Comment by michaelrockJAIA** [comment]
I also saw this last week

**Comment by edsanville** [comment]
Haven't heard much about this one... I think it was a rebuild_messages.sh thing.
