### ISSUE TITLE
run jaiabot simualtion

### ISSUE THREAD

**Issue by kangz543g** [jaiarobotics/jaiabot#1004]
question:
Launching the Simulator

Note: The Jaia simulator works with Ubuntu 20.04 and 22.04

    Clone the jaiabot repo (https://github.com/jaiarobotics/jaiabot)
    (install git if needed)
    sudo apt install git
    git clone https://github.com/jaiarobotics/jaiabot
    Run the setup scripts
    cd /path/to/jaiabot/scripts
    ./setup-tools-build.sh
    ./setup-tools-runtime.sh
    Run the build script
    cd /path/to/jaiabot
    ./build.sh
    Launch the JCC web interface
    cd /path/to/jaiabot/src/web
    ./run.sh
    Launch the simulator in a separate terminal
    cd /path/to/jaiabot/config/launch/simulation
    # Set the simulation to run 4 bots at a time warp of 5
    ./generate_all_launch.sh 4 5
    ./all.launch
    Troubleshooting the simulator

    Kill all processes
    # Kill all processes, then relaunch the simulator
    cd /path/to/jaiabot/scripts
    ./kill-jaiabot-processes.sh
    Refresh the build directory

# Remove the build directory
cd /path/to/jaiabot
rm -rf build
 
# Re-create the build directory
./build.sh

///////////////////////////////////////////////////////////////
1) run
 # Set the simulation to run 1 bots at a time warp of 2
 
    ./generate_all_launch.sh 1 2
    ./all.launch

link localhost:30002
![스크린샷(76)](https://github.com/user-attachments/assets/0d1c5d86-e553-4368-98c1-1e0426b8e813)

2) problem? 
   Launch the JCC web interface
    cd /path/to/jaiabot/src/web
    ./run.sh

link localhost:400001      # UDP : 40000 / TCP: 40001
![스크린샷(77)](https://github.com/user-attachments/assets/b858735d-fa48-41ee-94b5-853462f0483c)
run simualtion --> connect drroped to HUB (????????????????)  Do not know ????????

Thank you.

**Comment by ferrom-jaia** [comment]
Thank you for the screenshots. Can you post the output for the ./all.launch terminal?

**Comment by kangz543g** [comment]
service install

$ sudo nano /etc/systemd/system/jaiabot.service

////////////////////////////////////////////////////////////////

[Unit]
Description=Jaiabot Service
After=network.target

[Service]
Type=simple
User=course
WorkingDirectory=/home/course/jaiabot/src/web/server
ExecStart=/home/course/jaiabot/build/web_dev/python/venv/bin/python /home/course/jaiabot/src/web/server/app.py -a /home/course/jaiabot/build/web_dev
Restart=on-failure
Environment=PYTHONUNBUFFERED=1

[Install]
WantedBy=multi-user.target

////////////////////////////////////////////////////////////////

$ sudo systemctl daemon-reload
$ sudo systemctl restart jaiabot.service

$ sudo systemctl status jaiabot.service
● jaiabot.service - Jaiabot Service
     Loaded: loaded (/etc/systemd/system/jaiabot.service; enabled; vendor preset: enabled)
     Active: active (running) since Sat 2024-11-02 03:09:58 EDT; 2min 48s ago
   Main PID: 4044 (python3)
      Tasks: 6 (limit: 4584)
     Memory: 94.8M
     CGroup: /system.slice/jaiabot.service
             └─4044 /usr/bin/python3 /home/course/jaiabot/src/web/server/app.py -a /home/course/jaiabot/src/web/../..//build/web_dev/ -p 40000 -l INFO

Nov 02 03:12:25 neon python3[4044]: WARNING:root:🏓 Pinging server localhost:40000
Nov 02 03:12:25 neon python3[4044]: INFO:root:Sent 26 bytes
Nov 02 03:12:30 neon python3[4044]: WARNING:root:🏓 Pinging server localhost:40000
Nov 02 03:12:30 neon python3[4044]: INFO:root:Sent 26 bytes
Nov 02 03:12:35 neon python3[4044]: WARNING:root:🏓 Pinging server localhost:40000
Nov 02 03:12:35 neon python3[4044]: INFO:root:Sent 26 bytes
Nov 02 03:12:40 neon python3[4044]: WARNING:root:🏓 Pinging server localhost:40000
Nov 02 03:12:40 neon python3[4044]: INFO:root:Sent 26 bytes
Nov 02 03:12:45 neon python3[4044]: WARNING:root:🏓 Pinging server localhost:40000
Nov 02 03:12:45 neon python3[4044]: INFO:root:Sent 26 bytes

journalctl -u jaiabot.service -b

sudo journalctl -u jaiabot.service -f
course@neon:~/jaiabot/src/web/server$ sudo journalctl -u jaiabot.service -f
-- Logs begin at Wed 2021-03-03 14:30:52 EST. --
Nov 02 03:14:25 neon python3[4044]: WARNING:root:🏓 Pinging server localhost:40000
Nov 02 03:14:25 neon python3[4044]: INFO:root:Sent 26 bytes
Nov 02 03:14:35 neon python3[4044]: WARNING:root:🏓 Pinging server localhost:40000
Nov 02 03:14:35 neon python3[4044]: INFO:root:Sent 26 bytes
Nov 02 03:14:40 neon python3[4044]: WARNING:root:🏓 Pinging server localhost:40000
Nov 02 03:14:40 neon python3[4044]: INFO:root:Sent 26 bytes
Nov 02 03:14:45 neon python3[4044]: WARNING:root:🏓 Pinging server localhost:40000
Nov 02 03:14:45 neon python3[4044]: INFO:root:Sent 26 bytes
Nov 02 03:14:50 neon python3[4044]: WARNING:root:🏓 Pinging server localhost:40000
Nov 02 03:14:50 neon python3[4044]: INFO:root:Sent 26 bytes

**Comment by ferrom-jaia** [comment]
If you are still having issues you can try using our docker sim: 

https://github.com/jaiarobotics/jaiabot/blob/1.y/scripts/sim-docker/README.md

**Comment by kangz543g** [comment]
course@neon:~/jaiabot$ jaia status
>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>
                             ___       _   _ ___             
                      |  /\   |   /\  |_) / \ |              
                    \_| /--\ _|_ /--\ |_) \_/ |              

                       https://www.jaia.tech/                    
                   https://github.com/jaiarobotics/              
                           _ ___  _                              
                          |_  |  |_) |\/|                        
                          |  _|_ | \ |  |                        

  UNIT LOAD ACTIVE SUB DESCRIPTION
0 loaded units listed.
To show all installed unit files use 'systemctl list-unit-files'.
<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<
                               _   _   __ 
                          /\  |_) |_) (_  
                         /--\ |   |   __) 
                                          
  UNIT            LOAD   ACTIVE SUB     DESCRIPTION    
  jaiabot.service loaded active running Jaiabot Service

LOAD   = Reflects whether the unit definition was properly loaded.
ACTIVE = The high-level unit activation state, i.e. generalization of SUB.
SUB    = The low-level unit activation state, values depend on unit type.

1 loaded units listed.
To show all installed unit files use 'systemctl list-unit-files'.
<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<
                       _  _   __ ___  _        __ 
                 \  / |_ |_) (_   |  / \ |\ | (_  
                  \/  |_ | \ __) _|_ \_/ | \| __) 

jaiabot:
  1.14.0+0+g7698bc1a-dirty
  git hash: 7698bc1a6ad6405ab35a5704f1cd5eac5c4fd58c-dirty
  git branch: 1.y
goby: 3.1.5+0+ge8af3caf-dirty
moos: 10.4.0
ivp: 19.8.1+svn9395-10~ubuntu20.04.1
raspberry pi firmware: 
jaiabot rootfs image: 

>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>

**Comment by kangz543g** [comment]
![스크린샷(86)](https://github.com/user-attachments/assets/83164fd3-081a-45e1-bf29-2aa5526321ac)
![스크린샷(87)](https://github.com/user-attachments/assets/a3ea0da8-5c1c-41b6-9699-9e227f4c49fb)

**Comment by ferrom-jaia** [comment]
I am closing this for now as you are not responding to my previous suggestions.
