### ISSUE TITLE
error link?????

### ISSUE THREAD

**Issue by kangz543g** [jaiarobotics/jaiabot#1018]
error link????
![스크린샷 2024-11-18 19-20-17](https://github.com/user-attachments/assets/509b57ea-e165-47c0-baa6-77eeca11723e)

**Comment by ferrom-jaia** [comment]
Thank you for pointing this out!

We have a ticket to handle these links better in simulation. 

Currently those links will not work in sim. 

Great to see that you got the simulation up and running!

Did you use the docker sim or did you build the code?

**Comment by kangz543g** [comment]
Congratulations on your simulation success. http://10.23.0.11 user & password?

**Comment by kangz543g** [comment]
Launching the Simulator
Note: The Jaia simulator works with Ubuntu 20.04 and 22.04

Clone the jaiabot repo (https://github.com/jaiarobotics/jaiabot)
(install git if needed)
sudo apt install git
git clone https://github.com/jaiarobotics/jaiabot
Run the setup scripts
cd /path/to/jaiabot/scripts
./setup-tools-build.sh
./setup-tools-runtime.sh
Run the build script
cd /path/to/jaiabot
./build.sh
Launch the JCC web interface
cd /path/to/jaiabot/src/web
./run.sh
Launch the simulator in a separate terminal
cd /path/to/jaiabot/config/launch/simulation
# Set the simulation to run 4 bots at a time warp of 5
./generate_all_launch.sh 4 5
./all.launch
Troubleshooting the simulator
Kill all processes
# Kill all processes, then relaunch the simulator
cd /path/to/jaiabot/scripts
./kill-jaiabot-processes.sh
Refresh the build directory
# Remove the build directory
cd /path/to/jaiabot
rm -rf build
 
# Re-create the build directory
./build.sh

The result was a failure.    laugh ^^;

**Comment by ferrom-jaia** [comment]
Awesome, thank you for the feedback!
