### ISSUE TITLE
jaiabot 1.15.0 error?

### ISSUE THREAD

**Issue by kangz543g** [jaiarobotics/jaiabot#1033]
jaiabot 1.15.0 simualtion (error) ?????
![Screenshot from 2024-12-11 10-40-49](https://github.com/user-attachments/assets/f0374816-fe25-491a-8581-adf4b3cc3a80)

**Comment by kangz543g** [comment]
![Screenshot from 2024-12-11 10-40-48](https://github.com/user-attachments/assets/ecf1bd8e-d076-4ea1-80f8-b7218b5030b7)

**Comment by michael-jaia** [comment]
@kangz543g Thank you for posting this error. Pull request https://github.com/jaiarobotics/jaiabot/pull/1034 resolves the issue.
