### ISSUE TITLE
NVM install directory issue

### ISSUE THREAD

**Issue by seantfish** [jaiarobotics/jaiabot#887]
An EACCES error preceded by this error `./setup-tools-build-nodocker.sh: line 34: nvm: command not found` can occur if the install location of nvm is not `$HOME/.nvm`. Checking `XDG_CONFIG_HOME` may reveal the nvm install location to be `$HOME/.config/nvm`. This is caused by a behavior in the [install script](https://raw.githubusercontent.com/creationix/nvm/master/install.sh).

OS: Fedora Silverblue in Ubuntu 22.04 container

**Comment by seantfish** [comment]
The reasoning is provided [here](https://github.com/npm/rfcs/issues/389)

**Comment by ferrom-jaia** [comment]
Thank you Sean! We will add a ticket and fix.

**Comment by seantfish** [comment]
Thank you!
