### ISSUE TITLE
Error when building

### ISSUE THREAD

**Issue by E-Savage** [jaiarobotics/jaiabot#918]
I was attempting to use the build.sh script to build the software but it would seem that I ran into errors listed below
![jaiabotBuildError](https://github.com/jaiarobotics/jaiabot/assets/79065431/bf31765b-d306-40a3-85dc-25dab33dbd43)

I then tried using the cmake build option and I then received the following error but I did export the doxygen flag like the documentation said you could image below: 
![jaiabotBuildError2](https://github.com/jaiarobotics/jaiabot/assets/79065431/6799361b-bb51-49c2-ac97-7d8b70f76a75)

I am just kind of confused about what happened and I am not sure what to fix to get it to build properly using either method, any insights would be great and very helpful thank you for your time.

**Comment by michael-jaia** [comment]
Hey Eric thanks for posting. Did you run the `setup-tools-build.sh` and `setup-tools-run.sh` scripts in `jaiabot/scripts` first? I'm not sure if you saw these docs (https://github.com/jaiarobotics/jaiabot/blob/1.y/src/doc/markdown/page120_working_with_jaia_software.md) for launching the simulator.

**Comment by E-Savage** [comment]
Hello,

I have tried building the software after running the setup scripts and I have tried the one with out docker and it still gets stuck after 23% where it starts building npm settings. Is there a setting or a flag I should add to one of the scripts?

Sincerely,

Eric Savage

Sent from my Verizon, Samsung Galaxy smartphone
Get Outlook for Android<https://aka.ms/AAb9ysg>
________________________________

**Comment by E-Savage** [comment]
Hello, 

Thank you for your response I solved the issue I was having an issue with the version of protobuf, and downgrading it I had a clean install. Thank you for your help.
