### ISSUE TITLE
 run JCC????

### ISSUE THREAD

**Issue by kangz543g** [jaiarobotics/jaiabot#999]
Running the JCC
Please refer to the documentation in the repository for launching the simulator.

without readme????

**Comment by kangz543g** [comment]
localhost:40001

Do not connection dropped to hub???

http://localhost:40001/jaia/v0/status
error	"Connection Dropped To HUB"

run simualtor:
Launch the JCC web interface
cd /path/to/jaiabot/src/web
./run.sh
Launch the simulator in a separate terminal
cd /path/to/jaiabot/config/launch/simulation
# Set the simulation to run 4 bots at a time warp of 5
./generate_all_launch.sh 4 5
./all.launch

**Comment by ferrom-jaia** [comment]
Hello,

Please follow the following documentation: https://github.com/jaiarobotics/jaiabot/blob/1.y/src/doc/markdown/page120_working_with_jaia_software.md

If you run into issues, can you please post the error messages you are seeing.

Thank you!

**Comment by kangz543g** [comment]
plase jcc user video(https://www.youtube.com/@jaiarobotics1399) waypoint command.
please jcc simulator video
thank you.
